image: docker:latest

stages:
  - test

services:
  - docker:dind

test:
  stage: test
  before_script:
    - apk add --no-cache python3 py3-paramiko py3-cffi make
    - python3 -mpip install docker-compose
    - export ENVIRONMENT=local
  script:
    - make coverage
  coverage: '/TOTAL.*\s+(\d+%)$/'
